version: "3"
services:
  back-end:
    container_name: backcicd
    image: salem13/backcicd
    restart: always
    ports:
      - 8089:8089
    environment:
      MYSQL_HOST: mysqlCICD
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  db:
    container_name: mysqlCICD
    image: mysql
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: root